# $FreeBSD: projects/vps/lib/clang/libllvmlinker/Makefile 257008 2013-10-23 19:02:26Z will $

.include <bsd.own.mk>

LIB=	llvmlinker

SRCDIR=	lib/Linker
SRCS=	LinkModules.cpp

.include "../clang.lib.mk"
