#	$FreeBSD: projects/vps/tools/tools/ath/Makefile 257008 2013-10-23 19:02:26Z will $

SUBDIR=	arcode athdebug athdecode athkey athpoke athprom athrd athregs
SUBDIR+=	athstats ath_prom_read athradar athaggrstats
SUBDIR+=	ath_ee_v14_print ath_ee_v4k_print ath_ee_9287_print ath_ee_9300_print
SUBDIR+=	athsurvey athratestats athspectral

.include <bsd.subdir.mk>
