# $FreeBSD: projects/vps/lib/clang/libllvmobject/Makefile 257008 2013-10-23 19:02:26Z will $

.include <bsd.own.mk>

LIB=	llvmobject

SRCDIR=	lib/Object
SRCS=	Archive.cpp \
	Binary.cpp \
	COFFObjectFile.cpp \
	ELFObjectFile.cpp \
	Error.cpp \
	MachOObjectFile.cpp \
	Object.cpp \
	ObjectFile.cpp

.include "../clang.lib.mk"
