#!/bin/sh
#
# $FreeBSD: projects/vps/etc/rc.d/swap 257008 2013-10-23 19:02:26Z will $
#

# PROVIDE: swap
# REQUIRE: disks
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swap"
start_cmd='/sbin/swapon -aq'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
