#!/bin/sh
#
# $FreeBSD: projects/vps/etc/rc.d/swaplate 257008 2013-10-23 19:02:26Z will $
#

# PROVIDE: swaplate
# REQUIRE: mountlate
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="swaplate"
start_cmd='/sbin/swapon -aLq'
stop_cmd='/sbin/swapoff -aq'

load_rc_config swap
run_rc_command "$1"
