# $FreeBSD: projects/vps/usr.sbin/bsdconfig/examples/Makefile 257008 2013-10-23 19:02:26Z will $

NO_OBJ=

FILESDIR=	${SHAREDIR}/examples/bsdconfig
FILES=		browse_packages.sh bsdconfigrc

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
