# $FreeBSD: projects/vps/lib/clang/libllvmvectorize/Makefile 257008 2013-10-23 19:02:26Z will $

.include <bsd.own.mk>

LIB=	llvmvectorize

SRCDIR=	lib/Transforms/Vectorize
SRCS=	BBVectorize.cpp \
	LoopVectorize.cpp \
	SLPVectorizer.cpp \
	VecUtils.cpp \
	Vectorize.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
